# Generated by Django 5.0.1 on 2024-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='image',
            field=models.ImageField(default='profiles/astartes1.png', upload_to='profiles/images/'),
        ),
    ]
