# Generated by Django 5.0.1 on 2024-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0002_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='image',
            field=models.ImageField(upload_to='warhammer/video/'),
        ),
    ]
