# Generated by Django 5.0.1 on 2024-02-16 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0003_alter_videofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to='warhammer/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
