# Generated by Django 5.0.1 on 2024-02-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0004_alter_videofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='image',
            field=models.ImageField(upload_to='warhammer/images/'),
        ),
    ]
