# Generated by Django 5.0.1 on 2024-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0005_alter_videofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='warhammer/images/'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
