# Generated by Django 5.0.1 on 2024-03-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0007_remove_imagefile_author_imagefile_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='author',
        ),
    ]
