# Generated by Django 5.0.1 on 2024-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0008_remove_imagefile_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='author',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
