# Generated by Django 5.0.1 on 2024-03-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userpage_author'),
        ('warhammer', '0011_alter_imagefile_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.userpage'),
        ),
    ]
