# Generated by Django 5.0.1 on 2024-02-24 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='image',
            field=models.ImageField(default='users/images/1.jpg', null=True, upload_to='users/images/'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
