# Generated by Django 5.0.1 on 2024-02-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/images/'),
        ),
    ]
