# Generated by Django 5.0.1 on 2024-02-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
