# Generated by Django 5.0.1 on 2024-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='image',
            field=models.ImageField(default='users/astartes1.png', upload_to='users/images/'),
        ),
    ]
