# Generated by Django 5.0.1 on 2024-03-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userpage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPage',
        ),
    ]
